### ISSUE TITLE
Unable to use djnago-emoji app in dajngo-2.0.2

### ISSUE THREAD

**Issue by nishu112** [gaqzi/django-emoji#24]
i have installed django-emoji using pip command and put emoji in settings app.After that i am getting this error "django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'emoji.templatetags.emoji_tags': No module named 'django.core.urlresolvers'".Please look into this

**Comment by andres-torres-marroquin** [comment]
Have you tested the latest version 2.2.2? It seems to work to me, if it does for you, you should close this issue!

**Comment by skorokithakis** [comment]
Hmm, the latest version should work, yes.
